### ISSUE TITLE
Config decorator triggers render

### ISSUE THREAD

**Issue by joelricci** [Lundalogik/lime-web-components#104]
When the @config decorator is present a `render` is triggered from within `componentWillLoad`. 

Probably related some how to #75

**Comment by adrianschmidt** [comment]
As I wrote on #75, I think this is caused by using our decoration in combination with the `@State` decorator, and if `@State` is triggering a render before `componentWillLoad` has completed, that seems like a bug in Stencil. I'll take a closer look at it.

**Comment by joelricci** [comment]
> Edit: Nope, I was wrong. It reproduces even without the use of `@State`.

This is my experience as well (with Stencil 1.7.5).
