### ISSUE TITLE
Forms are not being rendered

### ISSUE THREAD

**Issue by TheGrandmother** [Lundalogik/lime-web-components#215]
I'm having a problem with `limel-forms` not rendering.
The `limel-form` tag is added to the dom but it is not populated with anything.

I'm getting no error messages or warnings either from the web-pack dev terminal or from the browser console.

The schema is:
```javascript
const schema = {
    title: 'Registration form',
    type: 'object',
    properties: {
        name: {
            type: 'string',
            title: 'Name',
        },
    },
};
```
And the render function is:
```javascript
    public render() {
        if (this.context.limetype !== 'document') {
            return;
        }

        return (
            <div>
            There should be stuff:
            <br />
            <limel-form
                schema={schema}
                value={this.formData}
            />
            </div>
        );
    }
```

But this is the only things that gets displayed in the document card:
![](https://i.imgur.com/Qr2rMVA.png)

I have essentially just copy pasted from [the documentation](http://lime-documentation-lime-elements.s3-website-eu-west-1.amazonaws.com/versions/26.29.0/form).
Am I missing something?

The forms seem to be pretty awesome and getting them to work would be a life saver as the integration I'm developing is pretty much just an bunch of forms.

Versions used:
lime-elements: 26.0.2
lime-web-components: 2.0.1
Chrome: 81.0.4044.129

**Comment by adrianschmidt** [comment]
Unfortunately, we didn't have limel-form in v26.0.2. The first version with limel-form is v26.5.0. A version of lime-elements with limel-form will be included in the next on-prem release, that Filip [mentioned](https://github.com/Lundalogik/lime-web-components/issues/214#issuecomment-650055191) on the other issue.

If your add-on isn't going to be used until a later version has been released and upgraded to, but you would like to develop for that later version already, we might be able to set you up with a later version that you can run locally. I'd have to clear that with someone obviously, but let me know if you would like me to look into it.

**Comment by TheGrandmother** [comment]
Ugh.... Okay. Thanks for the quick reply tho!
You should really mark the current documentation clearly that is for a version that has not yet been released, it is a bit confusing.

Cant I just upgrade `lime-elements` to the latest version tho?

Oki! We have no deadline for the release of this integration but I'll check with my bosses and contact our contact at Lime if this is a possible course of action (which I hope that it is since the forms element looks really nice).

**Comment by jgroth** [comment]
A small tip when developing something like this is to not write the schema on the frontend since JSONSchemas are very verbose, but instead use Marshmallow on the backend and serialize that to a JSONSchema in a custom endpoint. I have it on my TODO list to write a tutorial on how to do that :slightly_smiling_face:

**Comment by adrianschmidt** [comment]
> Ugh.... Okay. Thanks for the quick reply tho!
> You should really mark the current documentation clearly that is for a version that has not yet been released, it is a bit confusing.

Yeah, that's understandable. The problem is that we have no way of automatically updating that on release, so at the moment it would almost certainly become outdated at the moment we make a new release. And we also have our cloud environment, which is updated continuously. We're aware of the problem though 👍

> Cant I just upgrade `lime-elements` to the latest version tho?

You can upgrade lime-elements in your add-on, but the version used when installed is delivered by the Web Client, not by your add-on. So, unfortunately, no.

> Oki! We have no deadline for the release of this integration but I'll check with my bosses and contact our contact at Lime if this is a possible course of action (which I hope that it is since the forms element looks really nice).

Great! 👍

**Comment by TheGrandmother** [comment]
@jgroth I know I know, but I'm just trying go get going properly right now.

@adrianschmidt Okay! It was worth a shot :)

**Comment by TheGrandmother** [comment]
@adrianschmidt I've talked to my boss and he would be game with developing against the newer version.
Could you send me your email so I can include you in the discussion (or someone else's if you think someone else is more relavant) with scrive and our contacts within Lime?

**Comment by adrianschmidt** [comment]
> @adrianschmidt I've talked to my boss and he would be game with developing against the newer version.
> Could you send me your email so I can include you in the discussion (or someone else's if you think someone else is more relavant) with scrive and our contacts within Lime?

I'll ping in our product owners @magnusfagerlund and @FlippAre here, so they are aware of this (both are on vacation at the moment…)
@rka-lime and @erikmangsten: Ping, since you have been in contact with Henrik before.

**Comment by FlippAre** [comment]
Thank you @adrianschmidt!

@TheGrandmother  Please ping me if I can help you in anyway! I can recommend checking out our updated documentation: https://platform.docs.lime-crm.com/en/docs/

A lot of us are on vacation right now, or soon to be, so answers might take a bit longer than expected. Please don’t let that discourage you.

**Comment by TheGrandmother** [comment]
@FlippAre New documentation! :heart_eyes: 

Thanks a lot you guys!
I'll continue working on other parts of the integration in the meantime until someone has time to help me setup the new web-client version!

**Comment by FlippAre** [comment]
Following this, https://platform.docs.lime-crm.com/en/docs/getting-started/install-project/#development, and targeting lime-crm> 2.22.2 will give you a local dev environment with all the latest stuff

**Comment by TheGrandmother** [comment]
@FlippAre 
Wait wat.... Can I now run lime inside docker!?!?!?!?

**Comment by FlippAre** [comment]
Runs like a champ, and it is how we run it in our cloud in production. The desktop client still requires a Windows VM to run the LDC service. We will get rid of that dependency hopefully fairly soon.

**Comment by TheGrandmother** [comment]
OMFG!! Niiiiiice!! Having to run stuff on a Windows machine and RDPing all over the place on a unstable connection has been such a unimaginable pain.
Had we known this 6 months ago things would have gone so much smoother.
This is the best news I have received in a long while.

I'll try to see if I can get it upp and running on Ubuntu!

**Comment by TheGrandmother** [comment]
I'm getting an error from poetry saying:
`Because limepkg-scrive depends on lime-crm (>=2.22.2) which doesn't match any versions, version solving failed.`

This is the `pyproject.toml` file that I'm using:
```
[build-system]
requires      = ['poetry>=0.12']
build-backend = 'poetry.masonry.api'

[tool.metadata]
display_name  = ''
package_name  = 'limepkg-scrive'
lib_name      = 'limepkg_scrive'

[tool.poetry]
name        = 'limepkg-scrive'
version     = '0.1.0'
description = 'Lime CRM package'
authors     = ['Author <author@lime.tech>']

    [[tool.poetry.source]]
    name = 'lime'
    url  = 'https://pypi.lime.tech/simple/'

        [tool.poetry.plugins.'lime_plugins']
    'limepkg-scrive' = 'limepkg_scrive'

    [tool.poetry.dependencies]
    python = '~3.7.3'
    lime-crm = '>=2.22.2'

    [tool.poetry.dev-dependencies]
    click = '>=5.1'
    autopep8 = '>=1'
    flake8 = '>=2.1.0'
    ipdb = '>=0.8.1'
    pyreadline = '>=2.1'
    pytest-watch = '>=4.1.0'
    pytest = '<=5.0.1'

[tool.lime]
    [tool.lime.project]
    project_version = '1.26.0-poetry.20'
    project_type    = 'package'
    [[tool.lime.static_content]]
        [tool.lime.static_content.build_step]
        cwd = "frontend"
        commands = ["npm ci", "npm run build"]
        [tool.lime.static_content.copy_step]
        source = "frontend/dist"
        destination = "limepkg_scrive/web_components/static"
```

Has the latest `lime-crm` version not been published yet or am i missing something?
