### ISSUE TITLE
Multiline text input in lime forms?

### ISSUE THREAD

**Issue by TheGrandmother** [Lundalogik/lime-web-components#221]
Is there possible to have multi-line text input in `limel-form` ?
Essentially having the `textarea` input type in a form.
I haven't been able to find it in the docs.

**Comment by adrianschmidt** [comment]
Well, yes and no. We haven't added a component for wrapping our own textarea yet, but you can get a textarea by setting `"format": "textarea"` for a property of type string:

I tried adding a textarea in the form example called *Dynamic schema*:

```json
{
    "id": "test",
    "title": "My form",
    "description": "Lorem ipsum dolor sit amet",
    "type": "object",
    "required": [
        "title"
    ],
    "properties": {
        "title": {
            "type": "string",
            "title": "Title",
            "default": "A new task",
            "description": "Lorem ipsum dolor sit amet",
            "minLength": 5
        },
        "message": {
            "type": "string",
            "title": "Message",
            "description": "Write a message",
            "format": "textarea"
        },
        "done": {
            "type": "boolean",
            "title": "Done?",
            "default": false
        }
    }
}
```

And it comes out like this:
![image](https://user-images.githubusercontent.com/154725/87535217-6c721a80-c697-11ea-8a13-72ae684e1a2b.png)

**Comment by TheGrandmother** [comment]
Thanks!

I missed that from the dynamic schema part!
Thanks for the help :)
