### ISSUE TITLE
Add refactoring-tutorial

### ISSUE THREAD

**Issue by adrianschmidt** [Lundalogik/lime-web-components#31]
How to break up large chunks of code into smaller components. Avoiding one giant render-method.

**Comment by magnusfagerlund** [comment]
@adrianschmidt are you actively working on this issue?

**Comment by adrianschmidt** [comment]
@magnusfagerlund Not at the moment, no. I have a half-done thing I started on before my vacation.

**Comment by adrianschmidt** [comment]
@magnusfagerlund Here's what I've done so far: https://github.com/Lundalogik/lime-web-components/pull/32/files?short_path=e8fbc37#diff-e8fbc376cf5377474a996824bc5cb7d5
