### ISSUE TITLE
Usages of Event in lime-web-components

### ISSUE THREAD

**Issue by erikmangsten** [Lundalogik/lime-web-components#70]
When I tried to follow the documentation for "Hello, Event": https://lundalogik.github.io/lime-web-components/versions/latest/#/hello-event#listen-for-command-eventst

I ran into some problems regarding import/missing functions, specifically:  

> getCommandId, CreateLimeobjectDialogCommand and CommandEvent

I have solved the imports using these methods:
`import {getCommandId} from '@limetech/lime-web-components-interfaces/dist/service/commandbus-service';`

`import {CreateLimeobjectDialogCommand} from '@limetech/lime-web-components-commands'`

And adding 'CommandEvent' to the default import from 'lime-web-components'

I'm wondering if this is the correct way to import or if it should be included in the import from 'lime-web-components'? Also it would be great if these imports are specified in the documentation

## Environment

- **lime-web-components** version: 2.1.0
- **lime-project** version: 1.15
- **lime-webserver** version: 12.52.0.117

**Comment by adrianschmidt** [comment]
Thanks for the report!

You shouldn't have to import from anything other than `'@limetech/lime-web-components'`, so if you can't, you're _either_ using something that's meant to be internal, _or_ (probably more likely) we've forgotten to export it in the correct way. Seems like it's the latter in this case.

I'll list this as a bug and a documentation improvement 👍

**Comment by adrianschmidt** [comment]
I've taken a look, and `commandbus-service` seems to be exported correctly, so I'm pretty sure it should work if you import `getCommandId` like this: 

```ts
import {getCommandId} from '@limetech/lime-web-components-interfaces';
```

You're importing `CreateLimeobjectDialogCommand` correctly already.
