### ISSUE TITLE
Filters decorator trigger render

### ISSUE THREAD

**Issue by FredrikWallstrom** [Lundalogik/lime-web-components#75]
## Current behavior

When the component has some synchronous calls (await, async) to do in the componentWillLoad() method, the render method is suddenly called before the componentWillLoad method has completed.
It turns out that the problem appears when the @Filters decorator is used.

## Expected behavior

Completion of componentWillLoad() method even tough the @Filters decorator is used.

## Environment

- **lime-web-components** version: 2.0.0
- Framework used: Webclient
- Logs: No

**Comment by adrianschmidt** [comment]
`await` does not make a call synchronous. What it does is that it places all the code that appears after that statement (but still within the same function), into the `.then` block of the promise that is returned by the function that is called using `await`. So placing an `await` in `componentWillLoad` will not block other code from executing, and it shouldn't.

If you're making an asynchronous call in `componentWillLoad`, and you need to wait to render your component until that call completes, you can set a variable like `loaded`, and use that in your `render` function, to decide whether or not to render the component.

**Comment by jgroth** [comment]
> `await` does not make a call synchronous. What it does is that it places all the code that appears after that statement (but still within the same function), into the `.then` block of the promise that is returned by the function that is called using `await`. So placing an `await` in `componentWillLoad` will not block other code from executing, and it shouldn't.
> 
> If you're making an asynchronous call in `componentWillLoad`, and you need to wait to render your component until that call completes, you can set a variable like `loaded`, and use that in your `render` function, to decide whether or not to render the component.

If you make `componentWillLoad` asynchronous the render method will not be invoked until the promise returned from `componentWillLoad` is resolved. However, it appears that the `@Filters` decorator somehow messes this up :thinking:

**Comment by adrianschmidt** [comment]
> If you make `componentWillLoad` asynchronous the render method will not be invoked until the promise returned from `componentWillLoad` is resolved. However, it appears that the `@Filters` decorator (or something else) somehow messes this up 🤔

Ah! Thanks for the explanation! I did wonder if I was missing something 😄

I'll add this to the project board inbox.

**Comment by adrianschmidt** [comment]
Hmm… I thought about this a little, and I think the problem probably is that the `@filter` decorator is used in combination with the `@State` decorator, which triggers a render when the value is updated. If that's indeed the problem, that seems like a bug in Stencil to me. I'll see if I can look into it closer.

**Comment by adrianschmidt** [comment]
Nope… I was wrong. I can reproduce this using only one our our decorators, without `@State()`.

```tsx
import {
    LimeWebComponent,
    LimeWebComponentContext,
    LimeWebComponentPlatform,
    NotificationService,
    PlatformServiceName,
} from '@limetech/lime-web-components-interfaces';
import { Device } from '@limetech/lime-web-components-decorators';
import { Component, Element, h, Prop, State } from '@stencil/core';

@Component({
    tag: 'lwc-limepkg-event-tutorial-hello-world',
    shadow: true,
    styleUrl: 'lwc-limepkg-event-tutorial-hello-world.scss',
})
export class HelloWorld implements LimeWebComponent {
    @Prop()
    public platform: LimeWebComponentPlatform;

    @Prop()
    public context: LimeWebComponentContext;

    @Element()
    public element: HTMLElement;

    @State()
    private loaded = false;

    @Device()
    private device: string;

    constructor() {
        this.slow = this.slow.bind(this);
    }

    public async componentWillLoad() {
        console.log(this.device);
        await this.slow();
    }

    public render() {
        return this.loaded ? (
            <limel-button
                label={`Hello World!`}
                outlined={true}
                icon={'house_stark'}
                onClick={() => {
                    const notifications: NotificationService = this.platform.get(
                        PlatformServiceName.Notification
                    );
                    notifications.notify(`Winter is coming`);
                }}
            />
        ) : (<p>Oh crap!</p>);
    }

    private slow() {
        return new Promise(resolve => {
            setTimeout(() => {
                this.loaded = true;
                resolve('resolved');
            }, 2000);
        });
    }
}
```
